@startuml

package net.zero918nobita {
  package inverse {
    class Main {
      + {static} main(String[] args)
    }
  }

  package smilepp {
    package core {
      interface Pass
    }

    package frontend {
      class Addition {
        + void setVariable()
        + void setLeft()
        + void setRight()
        + String toString()
      }

      class AssignStm {
        + void setVariable()
        + void setValue()
        + String toString()
      }

      class Builder {
        + String toString()
        + void addStm()
        + void addLabel()
      }

      class IntLiteral {
        + String toString()
      }

      class IfStm {
      }

      abstract class Node
      abstract class Stm

      class Variable {
        + void setName(String name)
      }

      Addition <|-- Stm
      AssignStm <|-- Stm
      IfStm <|-- Stm
      IntLiteral <|-- Node
      Variable <|-- Node
    }
  }
}

@enduml
